{% set versions = {
    "1.0.0": "246add3d4b417312746b24e73e2abe79aae24bedc86c1db985c2697ff3ca9c22"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "difftop")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://difftop.hepforge.org/downloads/?f=difftop-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('gfortran') }}
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - make

  host:
    - lhapdf

  run:
    - lhapdf

about:
  home: "https://difftop.hepforge.org"
  license: "MIT"
  summary: "DiffTop: a code for the calculation of the differential cross section for heavy-quark pair production at hadron colliders"
  description: |
    DiffTop is the Fortran-based package which allows the user to calculate the differential and total cross section for heavy-quark pair production at hadron colliders in One-particle inclusive (1PI) kinematics. The cross sections are calculated in perturbative QCD at approximate next-to-next-to-leading order (approx.NNLO) by using methods of threshold resummation beyond the leading logarithmic accuracy.

extra:
  recipe-maintainers:
    - meiyasan
